### PR TITLE
Refactored schemas

### PR DESCRIPTION
**Pull request by cw-dvr8**
Move refactored schemas into production.

### CODE REVIEW

**Review by Aryllen — APPROVED** [review]
Looks good to me!

**Comment by Aryllen** [comment]
Oh, I see there's a conflicting file. Interestingly, GH will usually allow a person to resolve it in the web, but it won't on this one. Let me know if you would like some assistance fixing that.

**Comment by cw-dvr8** [comment]
@Aryllen I'd appreciate some help.  That directory doesn't exist anymore so I don't know how I'm supposed to resolve it.

**Comment by Aryllen** [comment]
This threw me for a loop for a moment! git was confused because the PEC_specific.json file had been altered on master/main, but was deleted in refactored-schemas. I had to add the master's version of the file back to refactored-schemas, commit, then delete and commit, again. It's all fixed now, though!

**Pull request merged**
