### PR TITLE
reference new STARRSeq template in config file

### PR DESCRIPTION
**Pull request by kelshmo**
@Aryllen I am trying to follow Cindy's offboarding to register a new template to Synapse. It looks like there was vision to have some automated jobs set up on this config but those jobs do not exist (or do they?). 

If not automated, do you know the steps to register a new schema to Synapse?

### CODE REVIEW

**Comment by Aryllen** [comment]
> I am trying to follow Cindy's offboarding to register a new template to Synapse. It looks like there was vision to have some automated jobs set up on this config but those jobs do not exist (or do they?).

Yes, automating this process was in the plan, but it isn't up and running, yet. I need to figure out the process for how this metadata/annotation ecosystem is managed, which I am going to start working on after the break. I'm hesitant to take the time to set up automation for what currently exists.

> If not automated, do you know the steps to register a new schema to Synapse?

I made an (somewhat disorganized) Rmarkdown in the past when I was first testing the schema functionality (geared towards Ljubo/Ryan). It has R functions I've made (some based off Kara's functions she wrote for synapseAnnotations). I'm also gathering these into an R package that is specific to the Synapse schema services. It's not on GH, yet, but is currently called schemann. I'll send you a link once I get it pushed up.

The challenge with these schemas, in particular, is that I don't know who has the ability to register new schemas to the sysbio.metadataTemplates organization. Additionally, Cindy has a script that generates your dictionary table based on PEC schemas.

How soon do you need STARRseq and the dictionary terms added (if any)? I can look into the org and getting it registered (even if that means starting a new org, which I hope doesn't need to happen).

**Comment by pitviper6** [comment]
@Aryllen @kelshmo We have a data upload that's stalled waiting for this template.

**Review by Aryllen — APPROVED** [review]

**Comment by Aryllen** [comment]
@pitviper6, alrighty. I'll get on this right now.

**Comment by kelshmo** [comment]
I dig the package name, schemann!!! Thanks for prioritizing this @Aryllen. Once it is on GH, I would love to help with development or testing so that the burden of registering new schemas is a distributed responsibility!

**Comment by Aryllen** [comment]
I'm glad you like the package name, @kelshmo, and appreciate the offer to help. 😊 

As I mentioned to @pitviper6 in slack, the STARRSeq template is now available for use. The PEC table still needs updated for validation in dccvalidator, but the dictionary inside the template file itself should be up to date. Testing out the table update now.

**Pull request merged**
