### PR TITLE
Convert dementia from Boolean to string

### PR DESCRIPTION
**Pull request by cw-dvr8**
dementia was originally defined as a Boolean, but this means that it will fail the dccvalidator if the value gets converted to upper case.  Change the typing to string so that values with different cases can be handled.

### CODE REVIEW

**Comment by kelshmo** [comment]
If the type is boolean - then case has no impact on how the dccvalidator interprets the value. Boolean types will be properly coerced. The problem is when the type is STRING; with enumerated values, exact matches will be enforced.

**Comment by kelshmo** [comment]
Since we do not need to enumerate values to include "unknown", I'm not sure why we need to change the type?

**Comment by cw-dvr8** [comment]
@kelshmo, the situation was when I created an individual metadata file that would fail the validator and put a value other than true/false in the dementia column (I think I put either "yes" or "no"), it not only flagged the invalid value, but the TRUE/FALSE values failed as well.  If there are no invalid values for this column, the Boolean values don't fail.  If this is not a scenario that we care about or think will happen, I can delete this PR.

**Comment by cw-dvr8** [comment]
@kelshmo if you want to try it, I used the individual_human_pass.csv and individual_human_fail.csv files that are in the Example Metadata Files folder.

**Comment by kelshmo** [comment]
I see that the fail message is not as descriptive as one might hope but this PR I don't think properly remedies the situation - the resolution would be to modify how the dccvalidator displays error messages. I will track this issue here: https://github.com/Sage-Bionetworks/dccvalidator/issues/316.

**Comment by cw-dvr8** [comment]
@kelshmo Sounds good, I'll delete the PR.

**Pull request closed without merging**
